#!/bin/sh /etc/rc.common

USE_PROCD=1
START=99
STOP=15

APP="/usr/share/freiheit/app.sh"

start_service() {
    procd_open_instance
    procd_set_param command $APP start
    procd_set_param respawn
    procd_close_instance
}    

stop_service() {
    $APP stop
}

reload_service() {
    stop
    start
}

service_triggers() {
    procd_add_reload_trigger "freiheit"
}
